#!/bin/bash
#
# Programm küsib kasutaja vanust 
# ja väljastab kirjelduse vastavalt vanusele
#
#
echo "Sisesta oma vanus"
read vanus

# hakkame vastavalt vanusele kirjeldust andma

if 
	test $vanus -gt 0 -a $vanus -lt 11
then 
        echo "Sa oled veel laps ;)"

elif
	 test $vanus -ge 11 -a $vanus -lt 18
then
        echo "Sa oled nooruk"

elif
	 test $vanus -ge 18 -a $vanus -lt 63
then
        echo "Sa oled täiskasvanu"
elif 
	test $vanus -ge 63
then
        echo "Sa oled seenior"
else
        echo "vigane sisend"
fi
