#!/bin/bash
#
# programm arvutab 10 esimese paarisarvu summa
#
#
kokku=0
# number peab olema väiksem kui 11
for (( number=1; number<11; number++ ))
do
	# kontroll, et oleks ikka paarisnumber
	number2=$(( $number % 2 ))
	if [ $number2 -eq 0 ];
	then
		# liidab ühe järgmise paarisarvu teiste summaga
		kokku=$(( $kokku + $number ))
		echo $kokku
	fi done
echo "Paarisarvude 1-10 summa on: $kokku"
#
# programmi lõpp
