#!/bin/bash
#
#Kolmnurga pindala arvutamine
#Heroni valemi abil
#
#skripti algus

echo
#Küsime külje A pikkuse
echo "Sisesta kylje A pikkus: "
read kylgA

#Küsime külje B pikkuse
echo "Sisesta kylje B pikkus: "
read kylgB

#Küsime külje C pikkust
echo "Sisesta kylje B pikkus: "
read kylgC

#hakkame arvutama
p=$(echo "scale=2; ($kylgA + $kylgB + $kylgC) / 2" | bc)

pindala=$(echo "scale=2; sqrt($p* ($p-$kylgA) * ($p-$kylgB) * ($p-$kylgC))" | bc)

echo "Kolmnurga pindala on: " $pindala
echo
#skripti lõpp
